const required = [
  "NETWORK_API_BASE_URL",
  "WEB_API_TOKEN",
  "WEB_SESSION_SECRET",
  "WEB_OWNER_PASSWORD_HASH",
];

const failures = [];
for (const name of required) {
  if (!process.env[name]?.trim()) failures.push(`${name} is missing`);
  if (process.env[`NEXT_PUBLIC_${name}`]) failures.push(`NEXT_PUBLIC_${name} must not be configured`);
}

try {
  const apiUrl = new URL(process.env.NETWORK_API_BASE_URL || "");
  if (apiUrl.protocol !== "https:") failures.push("NETWORK_API_BASE_URL must use HTTPS");
} catch {
  failures.push("NETWORK_API_BASE_URL must be a valid absolute URL");
}

if ((process.env.WEB_API_TOKEN || "").length < 32) failures.push("WEB_API_TOKEN must contain at least 32 characters");
if ((process.env.WEB_SESSION_SECRET || "").length < 32) failures.push("WEB_SESSION_SECRET must contain at least 32 characters");
if (process.env.WEB_API_TOKEN && process.env.WEB_API_TOKEN === process.env.WEB_SESSION_SECRET) failures.push("API and session secrets must be distinct");
if (!/^[0-9a-f]{32}:[0-9a-f]{128}$/.test(process.env.WEB_OWNER_PASSWORD_HASH || "")) failures.push("WEB_OWNER_PASSWORD_HASH must be generated by npm run hash-password");

const report = {
  passed: failures.length === 0,
  checks: required.map((name) => ({ name, configured: Boolean(process.env[name]?.trim()) })),
  failures,
};
process.stdout.write(`${JSON.stringify(report)}\n`);
if (failures.length) process.exitCode = 1;
